name: Terraform CI Pipeline

on:
  push:
    branches:
      - feature/**
      - develop

  pull_request:
    branches:
      - develop
      - main

  workflow_dispatch:

jobs:
  terraform-ci:
    name: Terraform Validation Pipeline

    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: eniverment/dev

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.0

      - name: Verify Terraform Version
        run: terraform version

      - name: Display Working Directory
        run: pwd

      - name: Display Repository Files
        run: ls -R


      - name: Terraform Format Check
        run: terraform fmt -check -recursive
        continue-on-error: true

      - name: Terraform Initialize
        run: terraform init -input=false

      - name: Terraform Validate
        run: terraform validate

      - name: Gitleaks Scan
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true

      - name: TruffleHog OSS Scan
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          base: ${{ github.event.repository.default_branch }}
          head: HEAD
          extra_args: --debug --only-verified
        continue-on-error: true

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4
      - name: Run TFLint
        run: tflint -f compact
        continue-on-error: true

      - name: Run tfsec
        uses: aquasecurity/tfsec-action@v1.0.3
        with:
          working_directory: eniverment/dev
          soft_fail: true

      - name: Setup Infracost
        uses: infracost/actions/setup@v3
        with:
          api-key: ${{ secrets.INFRACOST_API_KEY }}
        continue-on-error: true
      - name: Run Infracost
        run: infracost breakdown --path eniverment/dev
        continue-on-error: true

      # - name: Terraform Plan
      #   run: terraform plan -out=tfplan -input=false

      # - name: Upload Terraform Plan
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: terraform-plan
      #     path: eniverment/dev/tfplan

      - name: Pipeline Completed
        run: echo "Terraform CI Pipeline Completed Successfully!"