name: Terraform CD Pipeline

on:
  push:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: read

jobs:
  terraform-cd:
    name: Terraform Deployment

    runs-on: ubuntu-latest

    environment: Production

    defaults:
      run:
        shell: bash
        working-directory: eniverment/prod

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      # - name: Azure Login
      #   uses: azure/login@v2
      #   with:
      #     client-id: ${{ secrets.AZURE_CLIENT_ID }}
      #     tenant-id: ${{ secrets.AZURE_TENANT_ID }}
      #     subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      #     client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}

      # - name: Verify Azure Login
      #   run: az account show

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.0

      - name: Verify Terraform Version
        run: terraform version


      - name: Terraform Format Check
        run: terraform fmt -check -recursive
        continue-on-error: true

      - name: Terraform Initialize
        run: terraform init -input=false

      - name: Terraform Validate
        run: terraform validate

      # - name: Terraform Plan
      #   run: terraform plan -out=tfplan -input=false -no-color

      # - name: Upload Terraform Plan
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: terraform-plan
      #     path: eniverment/prod/tfplan

      # - name: Terraform Apply
      #   run: terraform apply -auto-approve tfplan

      # - name: Show Terraform Outputs
      #   run: terraform output